api-version: "1.21"
name: Salute
version: ${version}
main: codes.viremox.salute.paper.SalutePaperPlugin
authors:
  - viremox
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      load: BEFORE
      required: false
      join-classpath: true
